# Generated by Django 5.1.7 on 2025-03-22 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqmanpower',
            name='workerType',
            field=models.ForeignKey(db_column='workerType', on_delete=django.db.models.deletion.CASCADE, to='home.manpower'),
        ),
    ]
