# Generated by Django 5.1.7 on 2025-03-22 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_reqmanpower_requestid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drainage',
            name='areaCode',
            field=models.ForeignKey(db_column='areaCode', on_delete=django.db.models.deletion.CASCADE, to='home.area'),
        ),
        migrations.AlterField(
            model_name='reqmachine',
            name='machineType',
            field=models.ForeignKey(db_column='machineType', on_delete=django.db.models.deletion.CASCADE, to='home.machine'),
        ),
        migrations.AlterField(
            model_name='reqmachine',
            name='requestId',
            field=models.ForeignKey(db_column='requestId', on_delete=django.db.models.deletion.CASCADE, to='home.request'),
        ),
        migrations.AlterField(
            model_name='reqmaterial',
            name='materialType',
            field=models.ForeignKey(db_column='materialType', on_delete=django.db.models.deletion.CASCADE, to='home.material'),
        ),
        migrations.AlterField(
            model_name='reqmaterial',
            name='requestId',
            field=models.ForeignKey(db_column='requestId', on_delete=django.db.models.deletion.CASCADE, to='home.request'),
        ),
        migrations.AlterField(
            model_name='request',
            name='areaCode',
            field=models.ForeignKey(db_column='areaCode', on_delete=django.db.models.deletion.CASCADE, to='home.area'),
        ),
        migrations.AlterField(
            model_name='road',
            name='areaCode',
            field=models.ForeignKey(db_column='areaCode', on_delete=django.db.models.deletion.CASCADE, to='home.area'),
        ),
        migrations.AlterField(
            model_name='schedulingqueue',
            name='requestId',
            field=models.OneToOneField(db_column='requestId', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.request'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='requestId',
            field=models.OneToOneField(db_column='requestId', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.request'),
        ),
        migrations.AlterField(
            model_name='streetlight',
            name='areaCode',
            field=models.ForeignKey(db_column='areaCode', on_delete=django.db.models.deletion.CASCADE, to='home.area'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='areaCode',
            field=models.OneToOneField(db_column='areaCode', on_delete=django.db.models.deletion.CASCADE, to='home.area'),
        ),
        migrations.AlterField(
            model_name='user',
            name='areaCode',
            field=models.ForeignKey(db_column='areaCode', on_delete=django.db.models.deletion.CASCADE, to='home.area'),
        ),
    ]
